//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSisRRHH.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws5.pide.gob.pe/services/ReniecConsultaDni.ReniecConsultaDniHttpsSoap11En" +
            "dpoint")]
        public string MVCSisRRHH_reniec_pe_gob_pide_ws5_ReniecConsultaDni {
            get {
                return ((string)(this["MVCSisRRHH_reniec_pe_gob_pide_ws5_ReniecConsultaDni"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sdv.midis.gob.pe/Sis_WS/App/ReniecPersona_Servicio.svc")]
        public string MVCSisRRHH_pe_gob_midis_app_pruebas_ReniecPersona_Servicio {
            get {
                return ((string)(this["MVCSisRRHH_pe_gob_midis_app_pruebas_ReniecPersona_Servicio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://app1/Sis_WS/App/ReniecPersonaFoto_Servicio.svc")]
        public string MVCSisRRHH_reniec_pe_gob_midis_app1_ReniecPersonaFoto_Servicio {
            get {
                return ((string)(this["MVCSisRRHH_reniec_pe_gob_midis_app1_ReniecPersonaFoto_Servicio"]));
            }
        }
    }
}
