//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MVCSisRRHH.reniec.pe.gob.midis.app_pruebas {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IReniecPersona_Servicio", Namespace="http://tempuri.org/")]
    public partial class ReniecPersona_Servicio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarPorNumeroDeDocumentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReniecPersona_Servicio() {
            this.Url = global::MVCSisRRHH.Properties.Settings.Default.MVCSisRRHH_pe_gob_midis_app_pruebas_ReniecPersona_Servicio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarPorNumeroDeDocumentoCompletedEventHandler ConsultarPorNumeroDeDocumentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReniecPersona_Servicio/ConsultarPorNumeroDeDocumento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReniecPersona_Response ConsultarPorNumeroDeDocumento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ReniecPersona_Request peticion) {
            object[] results = this.Invoke("ConsultarPorNumeroDeDocumento", new object[] {
                        peticion});
            return ((ReniecPersona_Response)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPorNumeroDeDocumentoAsync(ReniecPersona_Request peticion) {
            this.ConsultarPorNumeroDeDocumentoAsync(peticion, null);
        }
        
        /// <remarks/>
        public void ConsultarPorNumeroDeDocumentoAsync(ReniecPersona_Request peticion, object userState) {
            if ((this.ConsultarPorNumeroDeDocumentoOperationCompleted == null)) {
                this.ConsultarPorNumeroDeDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPorNumeroDeDocumentoOperationCompleted);
            }
            this.InvokeAsync("ConsultarPorNumeroDeDocumento", new object[] {
                        peticion}, this.ConsultarPorNumeroDeDocumentoOperationCompleted, userState);
        }
        
        private void OnConsultarPorNumeroDeDocumentoOperationCompleted(object arg) {
            if ((this.ConsultarPorNumeroDeDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPorNumeroDeDocumentoCompleted(this, new ConsultarPorNumeroDeDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/APP.GSWEE.Entidades")]
    public partial class ReniecPersona_Request {
        
        private string claveField;
        
        private string numeroDeDocumentoField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumeroDeDocumento {
            get {
                return this.numeroDeDocumentoField;
            }
            set {
                this.numeroDeDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/APP.GSWEE.Entidades")]
    public partial class ReniecPersona_Registro {
        
        private string apellidoCasadaField;
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string direccionDomicilioField;
        
        private string distDomicilioField;
        
        private string dptoDomicilioField;
        
        private string fechaNacimientoField;
        
        private string nombresField;
        
        private string numeroDocumentoField;
        
        private string provDomicilioField;
        
        private string sexoField;
        
        private string ubigeoDistDomicilioField;
        
        private string ubigeoDptoDomicilioField;
        
        private string ubigeoProvDomicilioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApellidoCasada {
            get {
                return this.apellidoCasadaField;
            }
            set {
                this.apellidoCasadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DireccionDomicilio {
            get {
                return this.direccionDomicilioField;
            }
            set {
                this.direccionDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DistDomicilio {
            get {
                return this.distDomicilioField;
            }
            set {
                this.distDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DptoDomicilio {
            get {
                return this.dptoDomicilioField;
            }
            set {
                this.dptoDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProvDomicilio {
            get {
                return this.provDomicilioField;
            }
            set {
                this.provDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UbigeoDistDomicilio {
            get {
                return this.ubigeoDistDomicilioField;
            }
            set {
                this.ubigeoDistDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UbigeoDptoDomicilio {
            get {
                return this.ubigeoDptoDomicilioField;
            }
            set {
                this.ubigeoDptoDomicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UbigeoProvDomicilio {
            get {
                return this.ubigeoProvDomicilioField;
            }
            set {
                this.ubigeoProvDomicilioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/APP.GSWEE.Entidades")]
    public partial class ReniecPersona_Response {
        
        private string codigoField;
        
        private string mensajeField;
        
        private ReniecPersona_Registro personaDatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReniecPersona_Registro PersonaDato {
            get {
                return this.personaDatoField;
            }
            set {
                this.personaDatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ConsultarPorNumeroDeDocumentoCompletedEventHandler(object sender, ConsultarPorNumeroDeDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPorNumeroDeDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPorNumeroDeDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReniecPersona_Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReniecPersona_Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591